export const adminWebchatInboxCopy = {
  ko: {
    title: "웹 채팅",
    subtitle: "웹사이트 대화 • 이메일/WhatsApp과 함께 표시",
    refresh: "새로고침",
    loading: "불러오는 중...",
    failed: "목록을 불러오지 못했습니다",
    empty: "표시할 대화가 없습니다",
    show: "보기",
    close: "닫기",
    detailFailed: "상세를 불러오지 못했습니다",
    unknownLanguage: "언어 미확인",
    languageLabels: {
      ko: "한국어",
      en: "영어",
      ja: "일본어",
      zh: "중국어",
    },
    senderLabels: {
      customer: "고객",
      ai: "AI",
      admin: "상담사",
    },
    timeUnknown: "시간 미확인",
    olderLimited: "최근 50건 범위입니다. 전체 또는 미답변 건수가 아닙니다.",
    replyLabel: "답장",
    replyHint: "원문 텍스트를 그대로 검토해 회신합니다. 자동 번역/생성은 없음",
    replyPlaceholder: "회신 내용을 입력하세요",
    review: "검토",
    confirmTitle: "회신 확정",
    confirmHint: "고객은 검토한 원문 텍스트 그대로를 보게 됩니다",
    confirmSend: "고객에게 보내기",
    cancel: "취소",
    sending: "저장 중...",
    saved: "회신이 저장되었습니다. 발송/읽음은 확인되지 않습니다",
    retrySame: "같은 요청으로 다시 시도",
    uncertain: "응답 상태를 확인할 수 없습니다. 같은 요청으로 다시 시도하세요",
    stale: "새 메시지가 도착했습니다. 새로고침 후 다시 검토하세요",
    conflict: "요청 충돌이 발생했습니다. 목록을 새로고침하세요",
    unavailable: "현재 사용할 수 없습니다",
    notSent: "전송되지 않음",
    readOnlyPreview: "미리보기는 샘플 화면입니다. 실제 전송은 비활성화됨",
    previous: "이전",
    next: "다음",
    pageLabel: "페이지",
    customerLabel: "고객 대화",
    lastFromLabel: "마지막 발신",
    draftDiscardConfirm: "작성 중인 초안을 버리고 이동할까요?",
    replyRequired: "회신 내용을 입력하세요",
    locale: "ko-KR",
    unknownSender: "발신자 미확인",
  },
  en: {
    title: "Web Chat",
    subtitle: "Website conversations alongside company email and WhatsApp",
    refresh: "Refresh",
    loading: "Loading...",
    failed: "Failed to load conversations",
    empty: "No conversations to show",
    show: "Open",
    close: "Close",
    detailFailed: "Failed to load details",
    unknownLanguage: "Language unknown",
    languageLabels: {
      ko: "Korean",
      en: "English",
      ja: "Japanese",
      zh: "Chinese",
    },
    senderLabels: {
      customer: "Customer",
      ai: "AI",
      admin: "Agent",
    },
    timeUnknown: "Time unknown",
    olderLimited: "Latest 50 only, not a total or unanswered count.",
    replyLabel: "Reply",
    replyHint: "You will send the exact original text. No automatic translation or generation.",
    replyPlaceholder: "Type your reply",
    review: "Review",
    confirmTitle: "Confirm reply",
    confirmHint: "The customer will see only the exact reviewed text",
    confirmSend: "Send to customer",
    cancel: "Cancel",
    sending: "Saving...",
    saved: "Reply saved. Delivery and read status are not confirmed",
    retrySame: "Retry same request",
    uncertain: "Response is uncertain. Retry the same request only",
    stale: "New message arrived. Reload and review again",
    conflict: "Request conflict. Reload and retry",
    unavailable: "Currently unavailable",
    notSent: "Not sent",
    readOnlyPreview: "Preview is synthetic. Real sending is disabled",
    previous: "Previous",
    next: "Next",
    pageLabel: "Page",
    customerLabel: "Customer conversation",
    lastFromLabel: "Last from",
    draftDiscardConfirm: "Discard unsent draft and switch?",
    replyRequired: "Please enter a reply",
    locale: "en-US",
    unknownSender: "Unknown sender",
  },
  ja: {
    title: "ウェブチャット",
    subtitle: "ウェブサイト会話（会社メール/WhatsAppと並列表示）",
    refresh: "更新",
    loading: "読み込み中...",
    failed: "会話の取得に失敗しました",
    empty: "表示する会話がありません",
    show: "表示",
    close: "閉じる",
    detailFailed: "詳細の取得に失敗しました",
    unknownLanguage: "言語不明",
    languageLabels: {
      ko: "韓国語",
      en: "英語",
      ja: "日本語",
      zh: "中国語",
    },
    senderLabels: {
      customer: "顧客",
      ai: "AI",
      admin: "担当者",
    },
    timeUnknown: "時刻不明",
    olderLimited: "直近50件の範囲です。総件数や未返信数ではありません。",
    replyLabel: "返信",
    replyHint: "送信する文面は原文そのままです。自動翻訳・生成はありません",
    replyPlaceholder: "返信内容を入力してください",
    review: "確認",
    confirmTitle: "返信の確定",
    confirmHint: "顧客には確認済みの原文がそのまま表示されます",
    confirmSend: "お客様へ送信",
    cancel: "キャンセル",
    sending: "保存中...",
    saved: "返信を保存しました。送信/既読は確認されていません",
    retrySame: "同じリクエストを再試行",
    uncertain: "応答が不明です。新規作成せず同じリクエストを再試行してください",
    stale: "新しいメッセージが入りました。更新して再確認してください",
    conflict: "リクエスト競合です。再読み込みしてください",
    unavailable: "現在利用できません",
    notSent: "未送信",
    readOnlyPreview: "プレビューは表示用です。実送信は無効です",
    previous: "前へ",
    next: "次へ",
    pageLabel: "ページ",
    customerLabel: "顧客会話",
    lastFromLabel: "最終送信者",
    draftDiscardConfirm: "保存されていない下書きを破棄して切り替えますか？",
    replyRequired: "返信内容を入力してください",
    locale: "ja-JP",
    unknownSender: "送信者不明",
  },
  zh: {
    title: "网站聊天",
    subtitle: "网站会话（与公司邮箱/WhatsApp并列展示）",
    refresh: "刷新",
    loading: "加载中...",
    failed: "会话加载失败",
    empty: "暂无可显示会话",
    show: "打开",
    close: "关闭",
    detailFailed: "详情加载失败",
    unknownLanguage: "语言未知",
    languageLabels: {
      ko: "韩语",
      en: "英语",
      ja: "日语",
      zh: "中文",
    },
    senderLabels: {
      customer: "客户",
      ai: "AI",
      admin: "客服",
    },
    timeUnknown: "时间未知",
    olderLimited: "仅限最近50条，不代表总数或未回复数量。",
    replyLabel: "回复",
    replyHint: "仅发送原文内容。未进行自动翻译或生成",
    replyPlaceholder: "请输入回复内容",
    review: "复核",
    confirmTitle: "确认回复",
    confirmHint: "客户将看到您复核后的原始文本",
    confirmSend: "发送给客户",
    cancel: "取消",
    sending: "保存中...",
    saved: "回复已保存。未确认送达/已读状态",
    retrySame: "重试相同请求",
    uncertain: "响应状态未知，请重试同一请求，不要新建新请求",
    stale: "有新消息，请刷新后重新复核",
    conflict: "请求冲突，请重新加载",
    unavailable: "当前不可用",
    notSent: "未发送",
    readOnlyPreview: "为演示界面，真实发送已关闭",
    previous: "上一页",
    next: "下一页",
    pageLabel: "页码",
    customerLabel: "客户会话",
    lastFromLabel: "最近发起方",
    draftDiscardConfirm: "放弃未发送草稿并切换？",
    replyRequired: "请输入回复内容",
    locale: "zh-CN",
    unknownSender: "发送方未知",
  },
} as const;
