/**
 * country-dials.data — 전세계 국가번호 데이터 (~239국). 자동 생성, 직접 수정 금지.
 *
 * 생성기: scripts/gen-country-dials.mjs (ITU-T E.164 dial + Node Intl.DisplayNames 4언어명).
 * 갱신: dial 추가/수정 → 생성기 DIALS 갱신 → node scripts/gen-country-dials.mjs.
 *
 * lazy import 전용 — country-dials.ts 에서만 import (eager entry 번들 보호, check:size 게이트).
 *   flag emoji 는 데이터에 없음 — flagOf(code) 헬퍼가 ISO2 에서 파생.
 */
import type { CountryDial } from './country-dials';

export const RAW_COUNTRIES: ReadonlyArray<CountryDial> = [
  { code: "AD", dial: "376", name: { ko: "안도라", en: "Andorra", ja: "アンドラ", zh: "安道尔" } },
  { code: "AE", dial: "971", name: { ko: "아랍에미리트", en: "United Arab Emirates", ja: "アラブ首長国連邦", zh: "阿拉伯联合酋长国" } },
  { code: "AF", dial: "93", name: { ko: "아프가니스탄", en: "Afghanistan", ja: "アフガニスタン", zh: "阿富汗" } },
  { code: "AG", dial: "1268", name: { ko: "앤티가 바부다", en: "Antigua & Barbuda", ja: "アンティグア・バーブーダ", zh: "安提瓜和巴布达" } },
  { code: "AI", dial: "1264", name: { ko: "앵귈라", en: "Anguilla", ja: "アンギラ", zh: "安圭拉" } },
  { code: "AL", dial: "355", name: { ko: "알바니아", en: "Albania", ja: "アルバニア", zh: "阿尔巴尼亚" } },
  { code: "AM", dial: "374", name: { ko: "아르메니아", en: "Armenia", ja: "アルメニア", zh: "亚美尼亚" } },
  { code: "AO", dial: "244", name: { ko: "앙골라", en: "Angola", ja: "アンゴラ", zh: "安哥拉" } },
  { code: "AR", dial: "54", name: { ko: "아르헨티나", en: "Argentina", ja: "アルゼンチン", zh: "阿根廷" } },
  { code: "AS", dial: "1684", name: { ko: "아메리칸 사모아", en: "American Samoa", ja: "米領サモア", zh: "美属萨摩亚" } },
  { code: "AT", dial: "43", name: { ko: "오스트리아", en: "Austria", ja: "オーストリア", zh: "奥地利" } },
  { code: "AU", dial: "61", name: { ko: "오스트레일리아", en: "Australia", ja: "オーストラリア", zh: "澳大利亚" } },
  { code: "AW", dial: "297", name: { ko: "아루바", en: "Aruba", ja: "アルバ", zh: "阿鲁巴" } },
  { code: "AX", dial: "358", name: { ko: "올란드 제도", en: "Åland Islands", ja: "オーランド諸島", zh: "奥兰群岛" } },
  { code: "AZ", dial: "994", name: { ko: "아제르바이잔", en: "Azerbaijan", ja: "アゼルバイジャン", zh: "阿塞拜疆" } },
  { code: "BA", dial: "387", name: { ko: "보스니아 헤르체고비나", en: "Bosnia & Herzegovina", ja: "ボスニア・ヘルツェゴビナ", zh: "波斯尼亚和黑塞哥维那" } },
  { code: "BB", dial: "1246", name: { ko: "바베이도스", en: "Barbados", ja: "バルバドス", zh: "巴巴多斯" } },
  { code: "BD", dial: "880", name: { ko: "방글라데시", en: "Bangladesh", ja: "バングラデシュ", zh: "孟加拉国" } },
  { code: "BE", dial: "32", name: { ko: "벨기에", en: "Belgium", ja: "ベルギー", zh: "比利时" } },
  { code: "BF", dial: "226", name: { ko: "부르키나파소", en: "Burkina Faso", ja: "ブルキナファソ", zh: "布基纳法索" } },
  { code: "BG", dial: "359", name: { ko: "불가리아", en: "Bulgaria", ja: "ブルガリア", zh: "保加利亚" } },
  { code: "BH", dial: "973", name: { ko: "바레인", en: "Bahrain", ja: "バーレーン", zh: "巴林" } },
  { code: "BI", dial: "257", name: { ko: "부룬디", en: "Burundi", ja: "ブルンジ", zh: "布隆迪" } },
  { code: "BJ", dial: "229", name: { ko: "베냉", en: "Benin", ja: "ベナン", zh: "贝宁" } },
  { code: "BL", dial: "590", name: { ko: "생바르텔레미", en: "St. Barthélemy", ja: "サン・バルテルミー", zh: "圣巴泰勒米" } },
  { code: "BM", dial: "1441", name: { ko: "버뮤다", en: "Bermuda", ja: "バミューダ", zh: "百慕大" } },
  { code: "BN", dial: "673", name: { ko: "브루나이", en: "Brunei", ja: "ブルネイ", zh: "文莱" } },
  { code: "BO", dial: "591", name: { ko: "볼리비아", en: "Bolivia", ja: "ボリビア", zh: "玻利维亚" } },
  { code: "BQ", dial: "599", name: { ko: "네덜란드령 카리브", en: "Caribbean Netherlands", ja: "オランダ領カリブ", zh: "荷属加勒比区" } },
  { code: "BR", dial: "55", name: { ko: "브라질", en: "Brazil", ja: "ブラジル", zh: "巴西" } },
  { code: "BS", dial: "1242", name: { ko: "바하마", en: "Bahamas", ja: "バハマ", zh: "巴哈马" } },
  { code: "BT", dial: "975", name: { ko: "부탄", en: "Bhutan", ja: "ブータン", zh: "不丹" } },
  { code: "BW", dial: "267", name: { ko: "보츠와나", en: "Botswana", ja: "ボツワナ", zh: "博茨瓦纳" } },
  { code: "BY", dial: "375", name: { ko: "벨라루스", en: "Belarus", ja: "ベラルーシ", zh: "白俄罗斯" } },
  { code: "BZ", dial: "501", name: { ko: "벨리즈", en: "Belize", ja: "ベリーズ", zh: "伯利兹" } },
  { code: "CA", dial: "1", name: { ko: "캐나다", en: "Canada", ja: "カナダ", zh: "加拿大" } },
  { code: "CD", dial: "243", name: { ko: "콩고-킨샤사", en: "Congo - Kinshasa", ja: "コンゴ民主共和国(キンシャサ)", zh: "刚果（金）" } },
  { code: "CF", dial: "236", name: { ko: "중앙 아프리카 공화국", en: "Central African Republic", ja: "中央アフリカ共和国", zh: "中非共和国" } },
  { code: "CG", dial: "242", name: { ko: "콩고-브라자빌", en: "Congo - Brazzaville", ja: "コンゴ共和国(ブラザビル)", zh: "刚果（布）" } },
  { code: "CH", dial: "41", name: { ko: "스위스", en: "Switzerland", ja: "スイス", zh: "瑞士" } },
  { code: "CI", dial: "225", name: { ko: "코트디부아르", en: "Côte d’Ivoire", ja: "コートジボワール", zh: "科特迪瓦" } },
  { code: "CK", dial: "682", name: { ko: "쿡 제도", en: "Cook Islands", ja: "クック諸島", zh: "库克群岛" } },
  { code: "CL", dial: "56", name: { ko: "칠레", en: "Chile", ja: "チリ", zh: "智利" } },
  { code: "CM", dial: "237", name: { ko: "카메룬", en: "Cameroon", ja: "カメルーン", zh: "喀麦隆" } },
  { code: "CN", dial: "86", name: { ko: "중국", en: "China", ja: "中国", zh: "中国" } },
  { code: "CO", dial: "57", name: { ko: "콜롬비아", en: "Colombia", ja: "コロンビア", zh: "哥伦比亚" } },
  { code: "CR", dial: "506", name: { ko: "코스타리카", en: "Costa Rica", ja: "コスタリカ", zh: "哥斯达黎加" } },
  { code: "CU", dial: "53", name: { ko: "쿠바", en: "Cuba", ja: "キューバ", zh: "古巴" } },
  { code: "CV", dial: "238", name: { ko: "카보베르데", en: "Cape Verde", ja: "カーボベルデ", zh: "佛得角" } },
  { code: "CW", dial: "599", name: { ko: "퀴라소", en: "Curaçao", ja: "キュラソー", zh: "库拉索" } },
  { code: "CY", dial: "357", name: { ko: "키프로스", en: "Cyprus", ja: "キプロス", zh: "塞浦路斯" } },
  { code: "CZ", dial: "420", name: { ko: "체코", en: "Czechia", ja: "チェコ", zh: "捷克" } },
  { code: "DE", dial: "49", name: { ko: "독일", en: "Germany", ja: "ドイツ", zh: "德国" } },
  { code: "DJ", dial: "253", name: { ko: "지부티", en: "Djibouti", ja: "ジブチ", zh: "吉布提" } },
  { code: "DK", dial: "45", name: { ko: "덴마크", en: "Denmark", ja: "デンマーク", zh: "丹麦" } },
  { code: "DM", dial: "1767", name: { ko: "도미니카", en: "Dominica", ja: "ドミニカ国", zh: "多米尼克" } },
  { code: "DO", dial: "1809", name: { ko: "도미니카 공화국", en: "Dominican Republic", ja: "ドミニカ共和国", zh: "多米尼加共和国" } },
  { code: "DZ", dial: "213", name: { ko: "알제리", en: "Algeria", ja: "アルジェリア", zh: "阿尔及利亚" } },
  { code: "EC", dial: "593", name: { ko: "에콰도르", en: "Ecuador", ja: "エクアドル", zh: "厄瓜多尔" } },
  { code: "EE", dial: "372", name: { ko: "에스토니아", en: "Estonia", ja: "エストニア", zh: "爱沙尼亚" } },
  { code: "EG", dial: "20", name: { ko: "이집트", en: "Egypt", ja: "エジプト", zh: "埃及" } },
  { code: "ER", dial: "291", name: { ko: "에리트리아", en: "Eritrea", ja: "エリトリア", zh: "厄立特里亚" } },
  { code: "ES", dial: "34", name: { ko: "스페인", en: "Spain", ja: "スペイン", zh: "西班牙" } },
  { code: "ET", dial: "251", name: { ko: "에티오피아", en: "Ethiopia", ja: "エチオピア", zh: "埃塞俄比亚" } },
  { code: "FI", dial: "358", name: { ko: "핀란드", en: "Finland", ja: "フィンランド", zh: "芬兰" } },
  { code: "FJ", dial: "679", name: { ko: "피지", en: "Fiji", ja: "フィジー", zh: "斐济" } },
  { code: "FK", dial: "500", name: { ko: "포클랜드 제도", en: "Falkland Islands", ja: "フォークランド諸島", zh: "福克兰群岛" } },
  { code: "FM", dial: "691", name: { ko: "미크로네시아", en: "Micronesia", ja: "ミクロネシア連邦", zh: "密克罗尼西亚" } },
  { code: "FO", dial: "298", name: { ko: "페로 제도", en: "Faroe Islands", ja: "フェロー諸島", zh: "法罗群岛" } },
  { code: "FR", dial: "33", name: { ko: "프랑스", en: "France", ja: "フランス", zh: "法国" } },
  { code: "GA", dial: "241", name: { ko: "가봉", en: "Gabon", ja: "ガボン", zh: "加蓬" } },
  { code: "GB", dial: "44", name: { ko: "영국", en: "United Kingdom", ja: "イギリス", zh: "英国" } },
  { code: "GD", dial: "1473", name: { ko: "그레나다", en: "Grenada", ja: "グレナダ", zh: "格林纳达" } },
  { code: "GE", dial: "995", name: { ko: "조지아", en: "Georgia", ja: "ジョージア", zh: "格鲁吉亚" } },
  { code: "GF", dial: "594", name: { ko: "프랑스령 기아나", en: "French Guiana", ja: "仏領ギアナ", zh: "法属圭亚那" } },
  { code: "GG", dial: "44", name: { ko: "건지", en: "Guernsey", ja: "ガーンジー", zh: "根西岛" } },
  { code: "GH", dial: "233", name: { ko: "가나", en: "Ghana", ja: "ガーナ", zh: "加纳" } },
  { code: "GI", dial: "350", name: { ko: "지브롤터", en: "Gibraltar", ja: "ジブラルタル", zh: "直布罗陀" } },
  { code: "GL", dial: "299", name: { ko: "그린란드", en: "Greenland", ja: "グリーンランド", zh: "格陵兰" } },
  { code: "GM", dial: "220", name: { ko: "감비아", en: "Gambia", ja: "ガンビア", zh: "冈比亚" } },
  { code: "GN", dial: "224", name: { ko: "기니", en: "Guinea", ja: "ギニア", zh: "几内亚" } },
  { code: "GP", dial: "590", name: { ko: "과들루프", en: "Guadeloupe", ja: "グアドループ", zh: "瓜德罗普" } },
  { code: "GQ", dial: "240", name: { ko: "적도 기니", en: "Equatorial Guinea", ja: "赤道ギニア", zh: "赤道几内亚" } },
  { code: "GR", dial: "30", name: { ko: "그리스", en: "Greece", ja: "ギリシャ", zh: "希腊" } },
  { code: "GT", dial: "502", name: { ko: "과테말라", en: "Guatemala", ja: "グアテマラ", zh: "危地马拉" } },
  { code: "GU", dial: "1671", name: { ko: "괌", en: "Guam", ja: "グアム", zh: "关岛" } },
  { code: "GW", dial: "245", name: { ko: "기니비사우", en: "Guinea-Bissau", ja: "ギニアビサウ", zh: "几内亚比绍" } },
  { code: "GY", dial: "592", name: { ko: "가이아나", en: "Guyana", ja: "ガイアナ", zh: "圭亚那" } },
  { code: "HK", dial: "852", name: { ko: "홍콩(중국 특별행정구)", en: "Hong Kong SAR China", ja: "中華人民共和国香港特別行政区", zh: "中国香港特别行政区" } },
  { code: "HN", dial: "504", name: { ko: "온두라스", en: "Honduras", ja: "ホンジュラス", zh: "洪都拉斯" } },
  { code: "HR", dial: "385", name: { ko: "크로아티아", en: "Croatia", ja: "クロアチア", zh: "克罗地亚" } },
  { code: "HT", dial: "509", name: { ko: "아이티", en: "Haiti", ja: "ハイチ", zh: "海地" } },
  { code: "HU", dial: "36", name: { ko: "헝가리", en: "Hungary", ja: "ハンガリー", zh: "匈牙利" } },
  { code: "ID", dial: "62", name: { ko: "인도네시아", en: "Indonesia", ja: "インドネシア", zh: "印度尼西亚" } },
  { code: "IE", dial: "353", name: { ko: "아일랜드", en: "Ireland", ja: "アイルランド", zh: "爱尔兰" } },
  { code: "IL", dial: "972", name: { ko: "이스라엘", en: "Israel", ja: "イスラエル", zh: "以色列" } },
  { code: "IM", dial: "44", name: { ko: "맨섬", en: "Isle of Man", ja: "マン島", zh: "马恩岛" } },
  { code: "IN", dial: "91", name: { ko: "인도", en: "India", ja: "インド", zh: "印度" } },
  { code: "IO", dial: "246", name: { ko: "영국령 인도양 지역", en: "British Indian Ocean Territory", ja: "英領インド洋地域", zh: "英属印度洋领地" } },
  { code: "IQ", dial: "964", name: { ko: "이라크", en: "Iraq", ja: "イラク", zh: "伊拉克" } },
  { code: "IR", dial: "98", name: { ko: "이란", en: "Iran", ja: "イラン", zh: "伊朗" } },
  { code: "IS", dial: "354", name: { ko: "아이슬란드", en: "Iceland", ja: "アイスランド", zh: "冰岛" } },
  { code: "IT", dial: "39", name: { ko: "이탈리아", en: "Italy", ja: "イタリア", zh: "意大利" } },
  { code: "JE", dial: "44", name: { ko: "저지", en: "Jersey", ja: "ジャージー", zh: "泽西岛" } },
  { code: "JM", dial: "1876", name: { ko: "자메이카", en: "Jamaica", ja: "ジャマイカ", zh: "牙买加" } },
  { code: "JO", dial: "962", name: { ko: "요르단", en: "Jordan", ja: "ヨルダン", zh: "约旦" } },
  { code: "JP", dial: "81", name: { ko: "일본", en: "Japan", ja: "日本", zh: "日本" } },
  { code: "KE", dial: "254", name: { ko: "케냐", en: "Kenya", ja: "ケニア", zh: "肯尼亚" } },
  { code: "KG", dial: "996", name: { ko: "키르기스스탄", en: "Kyrgyzstan", ja: "キルギス", zh: "吉尔吉斯斯坦" } },
  { code: "KH", dial: "855", name: { ko: "캄보디아", en: "Cambodia", ja: "カンボジア", zh: "柬埔寨" } },
  { code: "KI", dial: "686", name: { ko: "키리바시", en: "Kiribati", ja: "キリバス", zh: "基里巴斯" } },
  { code: "KM", dial: "269", name: { ko: "코모로", en: "Comoros", ja: "コモロ", zh: "科摩罗" } },
  { code: "KN", dial: "1869", name: { ko: "세인트키츠 네비스", en: "St. Kitts & Nevis", ja: "セントクリストファー・ネーヴィス", zh: "圣基茨和尼维斯" } },
  { code: "KP", dial: "850", name: { ko: "북한", en: "North Korea", ja: "北朝鮮", zh: "朝鲜" } },
  { code: "KR", dial: "82", name: { ko: "대한민국", en: "South Korea", ja: "韓国", zh: "韩国" } },
  { code: "KW", dial: "965", name: { ko: "쿠웨이트", en: "Kuwait", ja: "クウェート", zh: "科威特" } },
  { code: "KY", dial: "1345", name: { ko: "케이맨 제도", en: "Cayman Islands", ja: "ケイマン諸島", zh: "开曼群岛" } },
  { code: "KZ", dial: "7", name: { ko: "카자흐스탄", en: "Kazakhstan", ja: "カザフスタン", zh: "哈萨克斯坦" } },
  { code: "LA", dial: "856", name: { ko: "라오스", en: "Laos", ja: "ラオス", zh: "老挝" } },
  { code: "LB", dial: "961", name: { ko: "레바논", en: "Lebanon", ja: "レバノン", zh: "黎巴嫩" } },
  { code: "LC", dial: "1758", name: { ko: "세인트루시아", en: "St. Lucia", ja: "セントルシア", zh: "圣卢西亚" } },
  { code: "LI", dial: "423", name: { ko: "리히텐슈타인", en: "Liechtenstein", ja: "リヒテンシュタイン", zh: "列支敦士登" } },
  { code: "LK", dial: "94", name: { ko: "스리랑카", en: "Sri Lanka", ja: "スリランカ", zh: "斯里兰卡" } },
  { code: "LR", dial: "231", name: { ko: "라이베리아", en: "Liberia", ja: "リベリア", zh: "利比里亚" } },
  { code: "LS", dial: "266", name: { ko: "레소토", en: "Lesotho", ja: "レソト", zh: "莱索托" } },
  { code: "LT", dial: "370", name: { ko: "리투아니아", en: "Lithuania", ja: "リトアニア", zh: "立陶宛" } },
  { code: "LU", dial: "352", name: { ko: "룩셈부르크", en: "Luxembourg", ja: "ルクセンブルク", zh: "卢森堡" } },
  { code: "LV", dial: "371", name: { ko: "라트비아", en: "Latvia", ja: "ラトビア", zh: "拉脱维亚" } },
  { code: "LY", dial: "218", name: { ko: "리비아", en: "Libya", ja: "リビア", zh: "利比亚" } },
  { code: "MA", dial: "212", name: { ko: "모로코", en: "Morocco", ja: "モロッコ", zh: "摩洛哥" } },
  { code: "MC", dial: "377", name: { ko: "모나코", en: "Monaco", ja: "モナコ", zh: "摩纳哥" } },
  { code: "MD", dial: "373", name: { ko: "몰도바", en: "Moldova", ja: "モルドバ", zh: "摩尔多瓦" } },
  { code: "ME", dial: "382", name: { ko: "몬테네그로", en: "Montenegro", ja: "モンテネグロ", zh: "黑山" } },
  { code: "MF", dial: "590", name: { ko: "생마르탱", en: "St. Martin", ja: "サン・マルタン", zh: "法属圣马丁" } },
  { code: "MG", dial: "261", name: { ko: "마다가스카르", en: "Madagascar", ja: "マダガスカル", zh: "马达加斯加" } },
  { code: "MH", dial: "692", name: { ko: "마셜 제도", en: "Marshall Islands", ja: "マーシャル諸島", zh: "马绍尔群岛" } },
  { code: "MK", dial: "389", name: { ko: "북마케도니아", en: "North Macedonia", ja: "北マケドニア", zh: "北马其顿" } },
  { code: "ML", dial: "223", name: { ko: "말리", en: "Mali", ja: "マリ", zh: "马里" } },
  { code: "MM", dial: "95", name: { ko: "미얀마", en: "Myanmar (Burma)", ja: "ミャンマー (ビルマ)", zh: "缅甸" } },
  { code: "MN", dial: "976", name: { ko: "몽골", en: "Mongolia", ja: "モンゴル", zh: "蒙古" } },
  { code: "MO", dial: "853", name: { ko: "마카오(중국 특별행정구)", en: "Macao SAR China", ja: "中華人民共和国マカオ特別行政区", zh: "中国澳门特别行政区" } },
  { code: "MP", dial: "1670", name: { ko: "북마리아나제도", en: "Northern Mariana Islands", ja: "北マリアナ諸島", zh: "北马里亚纳群岛" } },
  { code: "MQ", dial: "596", name: { ko: "마르티니크", en: "Martinique", ja: "マルティニーク", zh: "马提尼克" } },
  { code: "MR", dial: "222", name: { ko: "모리타니", en: "Mauritania", ja: "モーリタニア", zh: "毛里塔尼亚" } },
  { code: "MS", dial: "1664", name: { ko: "몬트세라트", en: "Montserrat", ja: "モントセラト", zh: "蒙特塞拉特" } },
  { code: "MT", dial: "356", name: { ko: "몰타", en: "Malta", ja: "マルタ", zh: "马耳他" } },
  { code: "MU", dial: "230", name: { ko: "모리셔스", en: "Mauritius", ja: "モーリシャス", zh: "毛里求斯" } },
  { code: "MV", dial: "960", name: { ko: "몰디브", en: "Maldives", ja: "モルディブ", zh: "马尔代夫" } },
  { code: "MW", dial: "265", name: { ko: "말라위", en: "Malawi", ja: "マラウイ", zh: "马拉维" } },
  { code: "MX", dial: "52", name: { ko: "멕시코", en: "Mexico", ja: "メキシコ", zh: "墨西哥" } },
  { code: "MY", dial: "60", name: { ko: "말레이시아", en: "Malaysia", ja: "マレーシア", zh: "马来西亚" } },
  { code: "MZ", dial: "258", name: { ko: "모잠비크", en: "Mozambique", ja: "モザンビーク", zh: "莫桑比克" } },
  { code: "NA", dial: "264", name: { ko: "나미비아", en: "Namibia", ja: "ナミビア", zh: "纳米比亚" } },
  { code: "NC", dial: "687", name: { ko: "뉴칼레도니아", en: "New Caledonia", ja: "ニューカレドニア", zh: "新喀里多尼亚" } },
  { code: "NE", dial: "227", name: { ko: "니제르", en: "Niger", ja: "ニジェール", zh: "尼日尔" } },
  { code: "NF", dial: "672", name: { ko: "노퍽섬", en: "Norfolk Island", ja: "ノーフォーク島", zh: "诺福克岛" } },
  { code: "NG", dial: "234", name: { ko: "나이지리아", en: "Nigeria", ja: "ナイジェリア", zh: "尼日利亚" } },
  { code: "NI", dial: "505", name: { ko: "니카라과", en: "Nicaragua", ja: "ニカラグア", zh: "尼加拉瓜" } },
  { code: "NL", dial: "31", name: { ko: "네덜란드", en: "Netherlands", ja: "オランダ", zh: "荷兰" } },
  { code: "NO", dial: "47", name: { ko: "노르웨이", en: "Norway", ja: "ノルウェー", zh: "挪威" } },
  { code: "NP", dial: "977", name: { ko: "네팔", en: "Nepal", ja: "ネパール", zh: "尼泊尔" } },
  { code: "NR", dial: "674", name: { ko: "나우루", en: "Nauru", ja: "ナウル", zh: "瑙鲁" } },
  { code: "NU", dial: "683", name: { ko: "니우에", en: "Niue", ja: "ニウエ", zh: "纽埃" } },
  { code: "NZ", dial: "64", name: { ko: "뉴질랜드", en: "New Zealand", ja: "ニュージーランド", zh: "新西兰" } },
  { code: "OM", dial: "968", name: { ko: "오만", en: "Oman", ja: "オマーン", zh: "阿曼" } },
  { code: "PA", dial: "507", name: { ko: "파나마", en: "Panama", ja: "パナマ", zh: "巴拿马" } },
  { code: "PE", dial: "51", name: { ko: "페루", en: "Peru", ja: "ペルー", zh: "秘鲁" } },
  { code: "PF", dial: "689", name: { ko: "프랑스령 폴리네시아", en: "French Polynesia", ja: "仏領ポリネシア", zh: "法属波利尼西亚" } },
  { code: "PG", dial: "675", name: { ko: "파푸아뉴기니", en: "Papua New Guinea", ja: "パプアニューギニア", zh: "巴布亚新几内亚" } },
  { code: "PH", dial: "63", name: { ko: "필리핀", en: "Philippines", ja: "フィリピン", zh: "菲律宾" } },
  { code: "PK", dial: "92", name: { ko: "파키스탄", en: "Pakistan", ja: "パキスタン", zh: "巴基斯坦" } },
  { code: "PL", dial: "48", name: { ko: "폴란드", en: "Poland", ja: "ポーランド", zh: "波兰" } },
  { code: "PM", dial: "508", name: { ko: "생피에르 미클롱", en: "St. Pierre & Miquelon", ja: "サンピエール島・ミクロン島", zh: "圣皮埃尔和密克隆群岛" } },
  { code: "PR", dial: "1787", name: { ko: "푸에르토리코", en: "Puerto Rico", ja: "プエルトリコ", zh: "波多黎各" } },
  { code: "PS", dial: "970", name: { ko: "팔레스타인 지구", en: "Palestinian Territories", ja: "パレスチナ自治区", zh: "巴勒斯坦领土" } },
  { code: "PT", dial: "351", name: { ko: "포르투갈", en: "Portugal", ja: "ポルトガル", zh: "葡萄牙" } },
  { code: "PW", dial: "680", name: { ko: "팔라우", en: "Palau", ja: "パラオ", zh: "帕劳" } },
  { code: "PY", dial: "595", name: { ko: "파라과이", en: "Paraguay", ja: "パラグアイ", zh: "巴拉圭" } },
  { code: "QA", dial: "974", name: { ko: "카타르", en: "Qatar", ja: "カタール", zh: "卡塔尔" } },
  { code: "RE", dial: "262", name: { ko: "레위니옹", en: "Réunion", ja: "レユニオン", zh: "留尼汪" } },
  { code: "RO", dial: "40", name: { ko: "루마니아", en: "Romania", ja: "ルーマニア", zh: "罗马尼亚" } },
  { code: "RS", dial: "381", name: { ko: "세르비아", en: "Serbia", ja: "セルビア", zh: "塞尔维亚" } },
  { code: "RU", dial: "7", name: { ko: "러시아", en: "Russia", ja: "ロシア", zh: "俄罗斯" } },
  { code: "RW", dial: "250", name: { ko: "르완다", en: "Rwanda", ja: "ルワンダ", zh: "卢旺达" } },
  { code: "SA", dial: "966", name: { ko: "사우디아라비아", en: "Saudi Arabia", ja: "サウジアラビア", zh: "沙特阿拉伯" } },
  { code: "SB", dial: "677", name: { ko: "솔로몬 제도", en: "Solomon Islands", ja: "ソロモン諸島", zh: "所罗门群岛" } },
  { code: "SC", dial: "248", name: { ko: "세이셸", en: "Seychelles", ja: "セーシェル", zh: "塞舌尔" } },
  { code: "SD", dial: "249", name: { ko: "수단", en: "Sudan", ja: "スーダン", zh: "苏丹" } },
  { code: "SE", dial: "46", name: { ko: "스웨덴", en: "Sweden", ja: "スウェーデン", zh: "瑞典" } },
  { code: "SG", dial: "65", name: { ko: "싱가포르", en: "Singapore", ja: "シンガポール", zh: "新加坡" } },
  { code: "SH", dial: "290", name: { ko: "세인트헬레나", en: "St. Helena", ja: "セントヘレナ", zh: "圣赫勒拿" } },
  { code: "SI", dial: "386", name: { ko: "슬로베니아", en: "Slovenia", ja: "スロベニア", zh: "斯洛文尼亚" } },
  { code: "SJ", dial: "47", name: { ko: "스발바르제도-얀마웬섬", en: "Svalbard & Jan Mayen", ja: "スバールバル諸島・ヤンマイエン島", zh: "斯瓦尔巴和扬马延" } },
  { code: "SK", dial: "421", name: { ko: "슬로바키아", en: "Slovakia", ja: "スロバキア", zh: "斯洛伐克" } },
  { code: "SL", dial: "232", name: { ko: "시에라리온", en: "Sierra Leone", ja: "シエラレオネ", zh: "塞拉利昂" } },
  { code: "SM", dial: "378", name: { ko: "산마리노", en: "San Marino", ja: "サンマリノ", zh: "圣马力诺" } },
  { code: "SN", dial: "221", name: { ko: "세네갈", en: "Senegal", ja: "セネガル", zh: "塞内加尔" } },
  { code: "SO", dial: "252", name: { ko: "소말리아", en: "Somalia", ja: "ソマリア", zh: "索马里" } },
  { code: "SR", dial: "597", name: { ko: "수리남", en: "Suriname", ja: "スリナム", zh: "苏里南" } },
  { code: "SS", dial: "211", name: { ko: "남수단", en: "South Sudan", ja: "南スーダン", zh: "南苏丹" } },
  { code: "ST", dial: "239", name: { ko: "상투메 프린시페", en: "São Tomé & Príncipe", ja: "サントメ・プリンシペ", zh: "圣多美和普林西比" } },
  { code: "SV", dial: "503", name: { ko: "엘살바도르", en: "El Salvador", ja: "エルサルバドル", zh: "萨尔瓦多" } },
  { code: "SX", dial: "1721", name: { ko: "신트마르턴", en: "Sint Maarten", ja: "シント・マールテン", zh: "荷属圣马丁" } },
  { code: "SY", dial: "963", name: { ko: "시리아", en: "Syria", ja: "シリア", zh: "叙利亚" } },
  { code: "SZ", dial: "268", name: { ko: "에스와티니", en: "Eswatini", ja: "エスワティニ", zh: "斯威士兰" } },
  { code: "TC", dial: "1649", name: { ko: "터크스 케이커스 제도", en: "Turks & Caicos Islands", ja: "タークス・カイコス諸島", zh: "特克斯和凯科斯群岛" } },
  { code: "TD", dial: "235", name: { ko: "차드", en: "Chad", ja: "チャド", zh: "乍得" } },
  { code: "TG", dial: "228", name: { ko: "토고", en: "Togo", ja: "トーゴ", zh: "多哥" } },
  { code: "TH", dial: "66", name: { ko: "태국", en: "Thailand", ja: "タイ", zh: "泰国" } },
  { code: "TJ", dial: "992", name: { ko: "타지키스탄", en: "Tajikistan", ja: "タジキスタン", zh: "塔吉克斯坦" } },
  { code: "TK", dial: "690", name: { ko: "토켈라우", en: "Tokelau", ja: "トケラウ", zh: "托克劳" } },
  { code: "TL", dial: "670", name: { ko: "동티모르", en: "Timor-Leste", ja: "東ティモール", zh: "东帝汶" } },
  { code: "TM", dial: "993", name: { ko: "투르크메니스탄", en: "Turkmenistan", ja: "トルクメニスタン", zh: "土库曼斯坦" } },
  { code: "TN", dial: "216", name: { ko: "튀니지", en: "Tunisia", ja: "チュニジア", zh: "突尼斯" } },
  { code: "TO", dial: "676", name: { ko: "통가", en: "Tonga", ja: "トンガ", zh: "汤加" } },
  { code: "TR", dial: "90", name: { ko: "튀르키예", en: "Türkiye", ja: "トルコ", zh: "土耳其" } },
  { code: "TT", dial: "1868", name: { ko: "트리니다드 토바고", en: "Trinidad & Tobago", ja: "トリニダード・トバゴ", zh: "特立尼达和多巴哥" } },
  { code: "TV", dial: "688", name: { ko: "투발루", en: "Tuvalu", ja: "ツバル", zh: "图瓦卢" } },
  { code: "TW", dial: "886", name: { ko: "대만", en: "Taiwan", ja: "台湾", zh: "台湾" } },
  { code: "TZ", dial: "255", name: { ko: "탄자니아", en: "Tanzania", ja: "タンザニア", zh: "坦桑尼亚" } },
  { code: "UA", dial: "380", name: { ko: "우크라이나", en: "Ukraine", ja: "ウクライナ", zh: "乌克兰" } },
  { code: "UG", dial: "256", name: { ko: "우간다", en: "Uganda", ja: "ウガンダ", zh: "乌干达" } },
  { code: "US", dial: "1", name: { ko: "미국", en: "United States", ja: "アメリカ合衆国", zh: "美国" } },
  { code: "UY", dial: "598", name: { ko: "우루과이", en: "Uruguay", ja: "ウルグアイ", zh: "乌拉圭" } },
  { code: "UZ", dial: "998", name: { ko: "우즈베키스탄", en: "Uzbekistan", ja: "ウズベキスタン", zh: "乌兹别克斯坦" } },
  { code: "VA", dial: "379", name: { ko: "바티칸 시국", en: "Vatican City", ja: "バチカン市国", zh: "梵蒂冈" } },
  { code: "VC", dial: "1784", name: { ko: "세인트빈센트그레나딘", en: "St. Vincent & Grenadines", ja: "セントビンセント及びグレナディーン諸島", zh: "圣文森特和格林纳丁斯" } },
  { code: "VE", dial: "58", name: { ko: "베네수엘라", en: "Venezuela", ja: "ベネズエラ", zh: "委内瑞拉" } },
  { code: "VG", dial: "1284", name: { ko: "영국령 버진아일랜드", en: "British Virgin Islands", ja: "英領ヴァージン諸島", zh: "英属维尔京群岛" } },
  { code: "VI", dial: "1340", name: { ko: "미국령 버진아일랜드", en: "U.S. Virgin Islands", ja: "米領ヴァージン諸島", zh: "美属维尔京群岛" } },
  { code: "VN", dial: "84", name: { ko: "베트남", en: "Vietnam", ja: "ベトナム", zh: "越南" } },
  { code: "VU", dial: "678", name: { ko: "바누아투", en: "Vanuatu", ja: "バヌアツ", zh: "瓦努阿图" } },
  { code: "WF", dial: "681", name: { ko: "왈리스-푸투나 제도", en: "Wallis & Futuna", ja: "ウォリス・フツナ", zh: "瓦利斯和富图纳" } },
  { code: "WS", dial: "685", name: { ko: "사모아", en: "Samoa", ja: "サモア", zh: "萨摩亚" } },
  { code: "YE", dial: "967", name: { ko: "예멘", en: "Yemen", ja: "イエメン", zh: "也门" } },
  { code: "YT", dial: "262", name: { ko: "마요트", en: "Mayotte", ja: "マヨット", zh: "马约特" } },
  { code: "ZA", dial: "27", name: { ko: "남아프리카", en: "South Africa", ja: "南アフリカ", zh: "南非" } },
  { code: "ZM", dial: "260", name: { ko: "잠비아", en: "Zambia", ja: "ザンビア", zh: "赞比亚" } },
  { code: "ZW", dial: "263", name: { ko: "짐바브웨", en: "Zimbabwe", ja: "ジンバブエ", zh: "津巴布韦" } },
];
