// PDF download generator. LOCKED region — extracted verbatim from
// src/pages/PlanDetailPage.tsx (L155-348) during P2 Lock release.
//
// Critical invariants (do not touch — PDF went blank when we broke these before):
//   1. container position MUST be on-screen (position:absolute; top:0; left:0).
//      Off-screen placement (left:-9999px) or display:none makes html2canvas render blank.
//   2. overlay (z-index:99998) over container (z-index:99997) hides the white sheet from
//      the user while html2canvas draws it.
//   3. CJK font-family fallback chain must stay intact so Korean/Japanese/Chinese glyphs
//      render instead of tofu boxes.
//   4. document.fonts.ready wait + 500ms settle + force reflow are required for first-run
//      font loading (esp. Korean).
//   5. iOS Safari path opens a blob in a new tab (worker.save() is often blocked).
//   6. Template literals stay ASCII-only — do not re-introduce emoji that could mojibake.
import { formatKRW } from './constants';
import type { PlanDocument, PlanDay, PlanStop, BudgetRow } from './types';

/** Optional i18n labels for PDF — pass planDetail.ui dict for current language */
export interface PdfUiDict {
  generatingPdf?: string;
  pdfDefaultTitle?: string;
  pdfArrivalGuide?: string;
  pdfDepartureGuide?: string;
  pdfBudgetSummary?: string;
  pdfOpenNaverMap?: string;
  pdfTip?: string;
  pdfReservationRequired?: string;
  pdfRecommended?: string;
  pdfFree?: string;
  pdfGeneratedBy?: string;
  budgetDay?: string;
  budgetTransport?: string;
  budgetEntry?: string;
  budgetMeals?: string;
  budgetTotal?: string;
  minUnit?: string;
  [key: string]: string | undefined;
}

export async function generatePDF(
  plan: PlanDocument,
  uiDict?: PdfUiDict,
  transitDict?: Record<string, string | undefined>,
  lang: string = 'en',
): Promise<void> {
  if (!plan) return;
  const it = plan.itinerary || {};
  const days = it.days || [];
  const arrival = it.arrival_guide;
  const departure = it.departure_guide;
  const budget = it.daily_budget_summary || [];
  const input = plan.input || {};

  // create render container - MUST be on-screen & fully expanded for html2canvas
  // Overlay (z-index:99998) sits on top to hide the white container from the user
  const overlay = document.createElement('div');
  overlay.style.cssText = 'position:fixed;top:0;left:0;right:0;bottom:0;z-index:99998;background:#0a0e1a;display:flex;align-items:center;justify-content:center;color:white;font-size:18px;font-family:system-ui;';
  const loadingText = uiDict?.generatingPdf || 'Generating PDF...';
  overlay.innerHTML = `<div style="text-align:center"><div style="width:40px;height:40px;border:3px solid #7C5CFC;border-top-color:transparent;border-radius:50%;animation:spin 1s linear infinite;margin:0 auto 16px"></div>${loadingText}</div><style>@keyframes spin{to{transform:rotate(360deg)}}</style>`;
  document.body.appendChild(overlay);

  const container = document.createElement('div');
  // position:absolute (not fixed) so container can expand beyond viewport height
  // left:0 (not -9999px) so html2canvas can actually render the content
  // CJK fallback chain: Noto Sans (Google Fonts preloaded) -> OS built-in -> generic
  // Noto Sans KR/JP/SC are preloaded in index.html for reliable CJK rendering
  container.style.cssText = 'position:absolute;top:0;left:0;width:800px;background:#ffffff;color:#1a1a2e;padding:40px;font-family:"Noto Sans KR","Noto Sans JP","Noto Sans SC","Segoe UI","Apple SD Gothic Neo","Malgun Gothic","Hiragino Sans","Microsoft JhengHei","Microsoft YaHei",system-ui,sans-serif;line-height:1.6;z-index:99997;';
  document.body.appendChild(container);

  // Color tokens for light PDF
  const C = {
    heading: '#1a1a2e',
    sub: '#555',
    muted: '#888',
    accent: '#7C5CFC',
    pink: '#EA537E',
    border: '#e0e0e0',
    cardBg: '#f8f9fc',
    transitBg: '#f0edff',
    budgetHead: '#7C5CFC',
  };

  // Title
  const L = {
    defaultTitle: uiDict?.pdfDefaultTitle || 'Your Korea Itinerary',
    arrivalGuide: uiDict?.pdfArrivalGuide || 'Airport Arrival Guide',
    departureGuide: uiDict?.pdfDepartureGuide || 'Departure Guide',
    budgetSummary: uiDict?.pdfBudgetSummary || 'Daily Budget Summary',
    openNaverMap: uiDict?.pdfOpenNaverMap || 'Open in Naver Map',
    tip: uiDict?.pdfTip || 'Tip',
    reservation: uiDict?.pdfReservationRequired || 'Reservation required',
    recommended: uiDict?.pdfRecommended || 'Recommended',
    free: uiDict?.pdfFree || 'Free',
    generatedBy: uiDict?.pdfGeneratedBy || 'Generated by CocoTrip AI',
    day: uiDict?.budgetDay || 'Day',
    transport: uiDict?.budgetTransport || 'Transport',
    entry: uiDict?.budgetEntry || 'Entry',
    meals: uiDict?.budgetMeals || 'Meals',
    total: uiDict?.budgetTotal || 'Total',
    min: uiDict?.minUnit || 'min',
  };
  let html = `<div style="text-align:center;margin-bottom:28px;padding-bottom:20px;border-bottom:2px solid ${C.accent};">
    <h1 style="font-size:26px;font-weight:800;color:${C.accent};margin:0 0 6px;">${it.tour_title || L.defaultTitle}</h1>
    <p style="color:${C.muted};font-size:13px;margin:0;">
      ${input.startDate || ''} | ${input.adults ? `${input.adults} adults` : `${input.pax || '-'} pax`}
      ${it.t_money_recommended_load ? ` | T-money: ${formatKRW(it.t_money_recommended_load)}` : ''}
    </p>
    <p style="color:${C.muted};font-size:10px;margin:4px 0 0;">${L.generatedBy} \u00B7 cocotripkr.com</p>
  </div>`;

  // Arrival Guide
  if (arrival) {
    html += `<div style="background:${C.cardBg};border:1px solid ${C.border};border-radius:10px;padding:16px;margin-bottom:16px;">
      <h3 style="font-size:15px;font-weight:700;color:${C.heading};margin:0 0 10px;">${L.arrivalGuide} \u2014 ${arrival.airport || ''}</h3>`;
    (arrival.steps || []).forEach((step: { step: number; title: string; description?: string; est_min?: number }) => {
      html += `<div style="margin:6px 0;padding:6px 0;border-bottom:1px solid ${C.border};">
        <p style="font-size:12px;color:${C.heading};margin:0;"><strong>Step ${step.step}: ${step.title}</strong></p>
        <p style="font-size:11px;color:${C.sub};margin:2px 0 0;">${step.description || ''}</p>
        ${(step.est_min || 0) > 0 ? `<p style="font-size:10px;color:${C.accent};margin:2px 0 0;">~${step.est_min} ${L.min}</p>` : ''}
      </div>`;
    });
    html += '</div>';
  }

  // All days
  days.forEach((day: PlanDay, di: number) => {
    html += `<div style="margin-bottom:24px;page-break-inside:avoid;">
      <div style="display:flex;align-items:center;gap:10px;margin-bottom:12px;">
        <div style="width:32px;height:32px;border-radius:50%;background:${C.accent};color:white;display:flex;align-items:center;justify-content:center;font-size:14px;font-weight:700;">${day.day || di + 1}</div>
        <div>
          <h2 style="font-size:16px;font-weight:700;color:${C.heading};margin:0;">${day.theme || `Day ${day.day || di + 1}`}</h2>
          ${day.date ? `<p style="font-size:10px;color:${C.muted};margin:0;">${day.date}</p>` : ''}
        </div>
      </div>`;

    (day.stops || []).forEach((stop: PlanStop) => {
      // Transit arrow (rich: uses steps_detail when available, falls back to step_by_step for legacy plans)
      if (stop.transit_from_prev) {
        const t = stop.transit_from_prev;
        const stepsDetail = (t.steps_detail as Array<Record<string, unknown>> | undefined) || [];
        const tr = {
          exit: transitDict?.exit || 'Exit',
          toward: transitDict?.toward || 'toward',
          stops: transitDict?.stops || 'stops',
          every: transitDict?.every || 'every',
          transfer: transitDict?.transfer || 'transfer',
          walk: transitDict?.walk || 'Walk',
          totalWalk: transitDict?.totalWalk || 'Total walk',
          min: L.min,
        };
        const transfers = (t as { transfers?: number }).transfers || 0;
        const totalWalk = (t as { total_walk_m?: number }).total_walk_m || 0;

        const summary = `${t.method} \u00B7 ${t.est_min || '?'}${tr.min}${(t.est_fare_krw || 0) > 0 ? ` \u00B7 ${formatKRW(t.est_fare_krw || 0)}` : ''}${transfers > 0 ? ` \u00B7 ${transfers} ${tr.transfer}` : ''}${t.source === 'odsay' ? ' [live]' : ''}`;

        let stepsHtml = '';
        if (stepsDetail.length > 0) {
          stepsHtml = stepsDetail.map((s) => {
            if (s.mode === 'subway') {
              // ja/zh: 한국어 + 한자 번역 병기 ("강남 (江南)", "2호선 (2号線)").
              // 한국어 primary는 현지 직원에게 보여줄 때 실용적, 괄호 안 한자는 사용자 이해용.
              // translate-plan API가 lineJa/lineZh/fromJa/... 를 채움. 없으면 lineEn/fromRoman으로 폴백.
              const trSuffix = lang === 'ja' ? 'Ja' : lang === 'zh' ? 'Zh' : '';
              const pickTr = (key: string): string | undefined =>
                trSuffix ? ((s as Record<string, unknown>)[`${key}${trSuffix}`] as string | undefined) : undefined;
              const lineKoStr = (s.lineKo as string) || '';
              const lineEnStr = (s.lineEn as string) || '';
              const lineTrStr = pickTr('line') || '';
              const lineLabel = lang === 'ko'
                ? (lineKoStr || (s.line as string) || '')
                : (lang === 'ja' || lang === 'zh')
                  ? (lineKoStr && (lineTrStr || lineEnStr) && lineKoStr !== (lineTrStr || lineEnStr)
                      ? `${lineKoStr} (${lineTrStr || lineEnStr})`
                      : (lineKoStr || lineTrStr || lineEnStr || (s.line as string) || ''))
                  : (lineEnStr || lineKoStr || (s.line as string) || '');
              // For ja/zh prefer translated Hanja; for en use roman; for ko show Korean only.
              const bilang = (ko: unknown, key: string, roman: unknown) => {
                const k = (ko as string) || '';
                if (!k) return '';
                if (lang === 'ko') return k;
                const tr = pickTr(key);
                const paren = tr || (roman as string | undefined);
                return paren ? `${k} (${paren})` : k;
              };
              const wayLabel = s.way ? bilang(s.way, 'way', s.wayRoman) : '';
              const fromLabel = bilang(s.from, 'from', s.fromRoman);
              const toLabel = bilang(s.to, 'to', s.toRoman);
              const head = `<b style="color:${C.accent};">${lineLabel}</b>${wayLabel ? ` <span style="color:${C.muted};font-weight:400;">(${tr.toward} ${wayLabel})</span>` : ''}`;
              const route = `<span style="color:#16a34a;">\u25CF ${fromLabel}${s.fromExit ? ` ${tr.exit} ${s.fromExit}` : ''}</span> \u2192 <span style="color:#db2777;">\u25CF ${toLabel}${s.toExit ? ` ${tr.exit} ${s.toExit}` : ''}</span>`;
              const meta = [
                s.stationCount ? `${s.stationCount} ${tr.stops}` : '',
                s.intervalMin ? `${tr.every} ${s.intervalMin}${tr.min}` : '',
                `${s.duration || '?'}${tr.min}`,
              ].filter(Boolean).join(' \u00B7 ');
              // Enrichment lines: transfer lines + accessibility + lost&found
              const fromInfo = s.fromStationInfo as { transferLines?: { lineKo: string; lineEn: string; lineKoJa?: string; lineKoZh?: string }[] } | undefined;
              const toInfo = s.toStationInfo as { hasElevator?: boolean; hasWheelchairLift?: boolean; lostCenterPhone?: string | null; address?: string | null } | undefined;
              const transferList = (fromInfo?.transferLines || []).map(l => {
                if (lang === 'ko') return l.lineKo;
                const trLine = lang === 'ja' ? l.lineKoJa : lang === 'zh' ? l.lineKoZh : undefined;
                if ((lang === 'ja' || lang === 'zh') && l.lineKo && trLine && l.lineKo !== trLine) {
                  return `${l.lineKo} (${trLine})`;
                }
                return l.lineEn || l.lineKo;
              }).filter(Boolean);
              const transferHtml = transferList.length > 0
                ? `<p style="font-size:8px;color:${C.muted};margin:2px 0 0;">\u21BB ${transitDict?.alsoTransfers || 'Also transfers'}: ${transferList.join(', ')}</p>`
                : '';
              const accessibleHtml = (toInfo?.hasElevator || toInfo?.hasWheelchairLift)
                ? `<p style="font-size:8px;color:#16a34a;margin:2px 0 0;">\u267F ${transitDict?.accessibleExit || 'Accessible exit available'}</p>`
                : '';
              const lostHtml = toInfo?.lostCenterPhone
                ? `<p style="font-size:8px;color:${C.muted};margin:2px 0 0;">${transitDict?.lostAndFound || 'Lost & found'}: ${toInfo.lostCenterPhone}</p>`
                : '';
              // First/last train: pick the direction matching this leg's `way`,
              // else fall back to whichever has data.
              const tt = s.fromTimetable as { up?: { first?: string; last?: string; lastDest?: string } | null; down?: { first?: string; last?: string; lastDest?: string } | null } | undefined;
              let chosenTrains: { first?: string; last?: string } | null = null;
              if (tt) {
                const way = s.way as string | undefined;
                const m = (t: { lastDest?: string } | null | undefined) => !!(t?.lastDest && way && (t.lastDest.includes(way) || way.includes(t.lastDest)));
                chosenTrains = m(tt.up) ? tt.up || null : m(tt.down) ? tt.down || null : (tt.up || tt.down || null);
              }
              const trainHtml = chosenTrains && (chosenTrains.first || chosenTrains.last)
                ? `<p style="font-size:8px;margin:2px 0 0;">${chosenTrains.first ? `<span style="color:${C.muted};">${transitDict?.firstTrain || 'First train'} ${chosenTrains.first}</span>` : ''}${chosenTrains.first && chosenTrains.last ? ' \u00B7 ' : ''}${chosenTrains.last ? `<span style="color:#db2777;font-weight:600;">${transitDict?.lastTrain || 'Last train'} ${chosenTrains.last}</span>` : ''}</p>`
                : '';
              return `<div style="margin:3px 0 3px 8px;padding:4px 8px;background:#ffffff;border:1px solid ${C.border};border-radius:4px;">
                <p style="font-size:10px;color:${C.heading};margin:0;">${head}</p>
                <p style="font-size:9px;color:${C.sub};margin:1px 0 0;">${route}</p>
                <p style="font-size:9px;color:${C.muted};margin:1px 0 0;">${meta}</p>
                ${trainHtml}${transferHtml}${accessibleHtml}${lostHtml}
              </div>`;
            }
            if (s.mode === 'bus') {
              // ja/zh 번역이 있으면 한국어 + 한자 병기. 없으면 한국어 그대로 (ODsay는 bus에 roman 미제공).
              const trSuffix = lang === 'ja' ? 'Ja' : lang === 'zh' ? 'Zh' : '';
              const sx = s as Record<string, unknown>;
              const bilangBus = (ko: string | undefined, key: string): string => {
                const k = ko || '';
                if (!k || lang === 'ko' || !trSuffix) return k;
                const tr = sx[`${key}${trSuffix}`] as string | undefined;
                return tr && tr !== k ? `${k} (${tr})` : k;
              };
              const busTypeLabel = bilangBus(s.busType as string | undefined, 'busType');
              const fromBus = bilangBus(s.from as string | undefined, 'from');
              const toBus = bilangBus(s.to as string | undefined, 'to');
              const head = `<b style="color:#16a34a;">${busTypeLabel ? `${busTypeLabel} ` : ''}${s.busNo || ''}</b>`;
              const route = `<span style="color:#16a34a;">\u25CF ${fromBus}${s.fromArs ? ` <span style="font-family:monospace;color:${C.muted};">#${s.fromArs}</span>` : ''}</span> \u2192 <span style="color:#db2777;">\u25CF ${toBus}${s.toArs ? ` <span style="font-family:monospace;color:${C.muted};">#${s.toArs}</span>` : ''}</span>`;
              const meta = [
                s.stationCount ? `${s.stationCount} ${tr.stops}` : '',
                s.intervalMin ? `${tr.every} ${s.intervalMin}${tr.min}` : '',
                `${s.duration || '?'}${tr.min}`,
              ].filter(Boolean).join(' \u00B7 ');
              return `<div style="margin:3px 0 3px 8px;padding:4px 8px;background:#ffffff;border:1px solid ${C.border};border-radius:4px;">
                <p style="font-size:10px;color:${C.heading};margin:0;">${head}</p>
                <p style="font-size:9px;color:${C.sub};margin:1px 0 0;">${route}</p>
                <p style="font-size:9px;color:${C.muted};margin:1px 0 0;">${meta}</p>
              </div>`;
            }
            // walk
            return `<p style="font-size:9px;color:${C.muted};margin:2px 0 2px 10px;">${tr.walk} ${s.duration || '?'}${tr.min}${(s.distance as number) > 0 ? ` (${s.distance}m)` : ''}</p>`;
          }).join('');
          if (totalWalk > 0) {
            stepsHtml += `<p style="font-size:8px;color:${C.muted};margin:3px 0 0 10px;">${tr.totalWalk}: ${totalWalk}m</p>`;
          }
        } else if (t.step_by_step?.length) {
          // Legacy plans generated before steps_detail existed — plain text fallback
          stepsHtml = t.step_by_step.map((s: string) => `<p style="font-size:9px;color:${C.sub};margin:1px 0 0 10px;">\u00B7 ${s}</p>`).join('');
        }

        html += `<div style="margin:4px 0 6px 16px;padding:6px 12px;background:${C.transitBg};border-left:3px solid ${C.accent};border-radius:4px;">
          <p style="font-size:10px;color:${C.accent};font-weight:700;margin:0;">${summary}</p>
          ${stepsHtml}
        </div>`;
      }

      // Stop card
      html += `<div style="background:${C.cardBg};border:1px solid ${C.border};border-radius:8px;padding:12px;margin-bottom:6px;">
        <div style="display:flex;justify-content:space-between;align-items:flex-start;">
          <div>
            <p style="font-size:13px;font-weight:700;color:${C.heading};margin:0;"><span style="color:${C.accent};font-size:12px;">${stop.start_time || ''}</span> \u00B7 ${stop.display_name || stop.name_en || stop.name || stop.name_ko || ''}</p>
            ${(stop.name || stop.name_ko) && (stop.display_name || stop.name_en) && (stop.name || stop.name_ko) !== (stop.display_name || stop.name_en) ? `<p style="font-size:10px;color:${C.muted};margin:2px 0 0;">${stop.name || stop.name_ko}</p>` : ''}
          </div>
          <span style="font-size:10px;color:${(stop.entry_fee_krw || 0) > 0 ? C.pink : '#22c55e'};font-weight:600;">${(stop.entry_fee_krw || 0) > 0 ? formatKRW(stop.entry_fee_krw || 0) : L.free}</span>
        </div>
        <p style="font-size:10px;color:${C.muted};margin:4px 0 0;">${stop.stay_min || '?'}min${stop.address ? ` | ${stop.address}` : ''}</p>
        ${stop.naverMapUrl ? `<p style="font-size:10px;margin:3px 0 0;"><a href="${stop.naverMapUrl}" style="color:${C.accent};text-decoration:underline;">${L.openNaverMap}</a></p>` : ''}
        ${(stop.tip || stop.tip_en) ? `<p style="font-size:10px;color:${C.sub};margin:4px 0 0;font-style:italic;">${L.tip}: ${stop.tip || stop.tip_en}</p>` : ''}
        ${stop.reservation_required ? `<p style="font-size:10px;color:#f97316;margin:4px 0 0;">${L.reservation}${stop.reservation_phone ? ` \u00B7 ${stop.reservation_phone}` : ''}</p>` : ''}
        ${stop.recommended_items?.length ? `<p style="font-size:10px;color:${C.sub};margin:4px 0 0;">${L.recommended}: ${stop.recommended_items.map((r: { name: string; price_krw?: number }) => `${r.name}${(r.price_krw || 0) > 0 ? ` (${formatKRW(r.price_krw!)})` : ''}`).join(', ')}</p>` : ''}
      </div>`;
    });
    html += '</div>';
  });

  // Budget table
  if (budget.length > 0) {
    html += `<div style="margin-bottom:20px;page-break-inside:avoid;">
      <h3 style="font-size:15px;font-weight:700;color:${C.heading};margin:0 0 10px;">${L.budgetSummary}</h3>
      <table style="width:100%;font-size:11px;border-collapse:collapse;border:1px solid ${C.border};">
        <tr style="background:${C.accent};color:white;">
          <th style="text-align:left;padding:8px;">${L.day}</th><th style="text-align:right;padding:8px;">${L.transport}</th><th style="text-align:right;padding:8px;">${L.entry}</th><th style="text-align:right;padding:8px;">${L.meals}</th><th style="text-align:right;padding:8px;">${L.total}</th>
        </tr>`;
    budget.forEach((row: BudgetRow, i: number) => {
      html += `<tr style="background:${i % 2 === 0 ? '#fff' : C.cardBg};border-bottom:1px solid ${C.border};">
        <td style="padding:6px 8px;font-weight:600;">${L.day} ${row.day}</td>
        <td style="text-align:right;padding:6px 8px;">${formatKRW(row.transport_krw || 0)}</td>
        <td style="text-align:right;padding:6px 8px;">${formatKRW(row.entry_fees_krw || 0)}</td>
        <td style="text-align:right;padding:6px 8px;">${formatKRW(row.meals_krw || 0)}</td>
        <td style="text-align:right;padding:6px 8px;font-weight:700;color:${C.accent};">${formatKRW(row.total_krw || 0)}</td>
      </tr>`;
    });
    const grandTotal = budget.reduce((s: number, r: BudgetRow) => s + (r.total_krw || 0), 0);
    html += `<tr style="background:${C.accent};color:white;font-weight:700;">
      <td style="padding:8px;" colspan="4">${L.total}</td>
      <td style="text-align:right;padding:8px;">${formatKRW(grandTotal)}</td>
    </tr>`;
    html += '</table></div>';
  }

  // Departure Guide
  if (departure) {
    html += `<div style="background:${C.cardBg};border:1px solid ${C.border};border-radius:10px;padding:16px;margin-bottom:16px;">
      <h3 style="font-size:15px;font-weight:700;color:${C.heading};margin:0 0 10px;">${L.departureGuide} \u2014 ${departure.airport || ''}</h3>`;
    if (departure.to_airport) {
      html += `<p style="font-size:11px;color:${C.sub};margin:0;">${departure.to_airport.method} \u00B7 ${departure.to_airport.instruction || ''} (${departure.to_airport.duration_min || '?'}min, ${formatKRW(departure.to_airport.cost_krw || 0)})</p>`;
    }
    if (departure.tax_refund) {
      html += `<p style="font-size:10px;color:${C.sub};margin:6px 0 0;">${uiDict?.taxRefund || 'Tax Refund'}: ${departure.tax_refund.location || ''} (${uiDict?.minPurchase || 'Min.'} ${formatKRW(departure.tax_refund.threshold_krw || 30000)})</p>`;
    }
    if (departure.last_minute_shopping) {
      html += `<p style="font-size:10px;color:${C.sub};margin:6px 0 0;">${uiDict?.lastMinuteShopping || 'Last-minute shopping'}: ${departure.last_minute_shopping}</p>`;
    }
    html += '</div>';
  }

  // Footer
  html += `<div style="text-align:center;border-top:1px solid ${C.border};padding-top:16px;margin-top:20px;">
    <p style="font-size:11px;color:${C.muted};margin:0;">WhatsApp: +82-10-8714-0611 | cocotripkr.com</p>
    <p style="font-size:9px;color:#bbb;margin:4px 0 0;">\u00A9 CocoTrip \u00B7 Korea Private Tour Specialist</p>
  </div>`;

  container.innerHTML = html;

  // === 빈 콘텐츠 방지: 최소 높이/텍스트 검증 ===
  if (container.scrollHeight < 100 || container.innerText.trim().length < 50) {
    console.error('[PDF] Empty content detected — aborting PDF generation');
    document.body.removeChild(container);
    document.body.removeChild(overlay);
    alert('PDF content is empty. Please wait for the plan to fully load.');
    return;
  }

  // Wait for browser to fully render the content (especially Korean fonts)
  // document.fonts.ready resolves when all font faces are loaded
  await Promise.race([
    document.fonts?.ready || Promise.resolve(),
    new Promise(resolve => setTimeout(resolve, 3000)),
  ]);

  // === CJK 폰트 렌더 검증: 더미 문자로 실제 렌더 확인 ===
  const fontTest = document.createElement('span');
  fontTest.style.cssText = 'position:absolute;top:-9999px;font-size:16px;font-family:inherit;';
  fontTest.textContent = '\uD55C\uAE00\u30C6\u30B9\u30C8\u4E2D\u6587';
  container.appendChild(fontTest);
  await new Promise(resolve => setTimeout(resolve, 300));
  if (fontTest.offsetWidth === 0) {
    console.warn('[PDF] CJK font may not be loaded — proceeding with system fallback');
  }
  fontTest.remove();

  // Additional settle time for layout recalculation
  await new Promise(resolve => setTimeout(resolve, 500));
  void container.offsetHeight; // force reflow

  try {
    const html2pdf = (await import('html2pdf.js')).default;
    const titleSlug = (it.tour_title || 'korea-trip').replace(/[^a-zA-Z0-9\s-]/g, '').replace(/\s+/g, '-').slice(0, 40) || 'korea-trip';
    const dateStr = input.startDate || 'undated';
    const filename = `cocotrip-${titleSlug}-${dateStr}.pdf`;

    const worker = html2pdf().set({
      margin: [8, 8, 8, 8],
      filename,
      image: { type: 'jpeg', quality: 0.98 },
      html2canvas: { scale: 1.5, useCORS: true, logging: false, backgroundColor: '#ffffff', windowWidth: 800, scrollX: 0, scrollY: 0 },
      jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' },
      pagebreak: { mode: ['avoid-all', 'css', 'legacy'] },
    } as Record<string, unknown>).from(container);

    // iOS Safari: direct .save() often blocked -> open blob in new tab
    if (/iPhone|iPad|iPod/i.test(navigator.userAgent)) {
      const pdf = await worker.outputPdf('blob');
      const url = URL.createObjectURL(pdf);
      window.open(url, '_blank');
      setTimeout(() => URL.revokeObjectURL(url), 60000);
    } else {
      await worker.save();
    }
  } catch (err) {
    console.error('[PDF] generation failed:', err);
    alert('PDF generation failed. Please try again or contact us via WhatsApp.');
  } finally {
    document.body.removeChild(container);
    document.body.removeChild(overlay);
  }
}
