import type { Language } from '@/i18n';

// Spark drafted the four-language copy; final wording distinguishes acceptance from delivery.
const ko = {
  title: '내 폰 알림 시험', check: '이 기기 연결 확인', send: '이 기기에 시험 알림 보내기',
  checking: '서버의 알림 대상과 이 기기를 확인하고 있습니다.', sending: '시험 알림 요청 중',
  initial: '먼저 이 기기를 등록한 뒤 연결을 확인하세요. 확인 버튼만으로는 알림을 보내지 않습니다.',
  ready: '이 기기가 서버의 알림 대상으로 지정되어 있습니다.',
  disabled: '서버 자동 알림 설정이 먼저 필요합니다. 기기 등록만으로 켜지지 않습니다.',
  notSelected: '이 기기는 서버에 지정된 알림 대상이 아닙니다. 다른 기기로 보내지 않았습니다.',
  notReady: '연결을 확인하지 못했습니다. 로그인·기기 등록·알림 허용 상태를 확인하세요.',
  accepted: '알림 서비스가 요청을 접수했습니다. 실제 도착 여부는 폰에서 확인해 주세요.',
  unknown: '발송 결과를 확인하지 못했습니다. 중복 방지를 위해 다시 보내지 않습니다. 폰을 먼저 확인해 주세요.',
  rejected: '알림 요청이 거절되었습니다. 기기 연결 설정을 확인해 주세요.',
  busy: '기존 시험 요청을 처리 중이거나 대기 시간이 필요합니다. 자동 재발송은 하지 않습니다.',
  alreadyHandled: '이미 처리한 시험 요청입니다. 다시 보내지 않았습니다.',
  review: '시험 기록 점검이 필요해 발송을 잠갔습니다. 실제 폰 수신과 서버 기록을 먼저 확인해야 합니다.',
};
type Copy = Record<keyof typeof ko, string>;
export const ownerDeviceTestCopy: Record<Language, Copy> = {
  ko,
  en: {
    title: 'Test my phone notification', check: 'Check this device', send: 'Send a test to this device',
    checking: 'Checking whether this device is the server-selected recipient.', sending: 'Requesting a test notification',
    initial: 'Register this device first, then check its connection. Checking does not send a notification.',
    ready: 'This device matches the server-selected notification recipient.',
    disabled: 'Server automatic notification setup is required first. Device registration does not enable it.',
    notSelected: 'This is not the server-selected device. Nothing was sent to another device.',
    notReady: 'Could not verify the connection. Check sign-in, device registration and notification permission.',
    accepted: 'The notification service accepted the request. Check your phone to confirm arrival.',
    unknown: 'The send result is unknown. To avoid duplicates, we will not resend. Check your phone first.',
    rejected: 'The notification request was rejected. Check the device connection settings.',
    busy: 'A test request is pending or a waiting period applies. No automatic resend will occur.',
    alreadyHandled: 'This test request was already handled. It was not sent again.',
    review: 'Sending is locked pending a test-record review. Check the phone and server records first.',
  },
  ja: {
    title: '自分のスマホで通知テスト', check: 'この端末の接続を確認', send: 'この端末にテスト通知を送る',
    checking: 'この端末がサーバーの通知先か確認しています。', sending: 'テスト通知をリクエスト中',
    initial: '端末を登録してから接続を確認してください。確認だけでは通知を送りません。',
    ready: 'この端末はサーバーの通知先に指定されています。',
    disabled: '先にサーバーの自動通知設定が必要です。端末登録だけでは有効になりません。',
    notSelected: 'この端末は指定された通知先ではありません。他の端末にも送っていません。',
    notReady: '接続を確認できません。ログイン・端末登録・通知の許可をご確認ください。',
    accepted: '通知サービスがリクエストを受け付けました。実際の受信はスマホでご確認ください。',
    unknown: '送信結果が不明です。重複を防ぐため再送しません。まずスマホをご確認ください。',
    rejected: '通知リクエストが拒否されました。端末の接続設定をご確認ください。',
    busy: '先のテストを処理中、または待機が必要です。自動で再送しません。',
    alreadyHandled: 'このテストは処理済みです。再送していません。',
    review: 'テスト記録の確認が必要なため送信を停止しています。端末の受信とサーバー記録を先にご確認ください。',
  },
  zh: {
    title: '我的手机通知测试', check: '检查当前设备连接', send: '向该设备发送测试通知',
    checking: '正在检查该设备是否为服务器指定的通知接收设备。', sending: '正在发送测试通知请求',
    initial: '请先注册该设备，再检查连接。检查连接不会发送通知。',
    ready: '该设备是服务器指定的通知接收设备。',
    disabled: '请先完成服务器自动通知设置。仅注册设备不会启用自动通知。',
    notSelected: '该设备不是指定的通知接收设备，也未向其他设备发送。',
    notReady: '无法确认连接，请检查登录、设备注册及通知权限。',
    accepted: '通知服务已接受请求，请在手机上确认是否实际收到。',
    unknown: '发送结果未知。为避免重复，我们不会再次发送。请先检查手机。',
    rejected: '通知请求被拒绝，请检查设备连接设置。',
    busy: '先前的测试正在处理或需要等待，不会自动重发。',
    alreadyHandled: '该测试请求已处理，未再次发送。',
    review: '需要检查测试记录，发送已锁定。请先确认手机接收情况及服务器记录。',
  },
};
