import type { Language } from '@/i18n';

const ko = {
  title: '오너 컨트롤러 설치',
  installed: 'Control 앱 화면으로 실행 중',
  installAccepted: '홈 화면 웹 앱 설치 요청됨',
  reload: '새로고침',
  updateLine: '웹 화면은 배포 후 업데이트 안내 또는 새로고침으로 변경사항을 반영합니다.',
  installDetail: '홈 화면에서 바로 열려면 아래 설치 안내를 확인하세요.',
  updateTitle: '웹 화면 업데이트',
  updateDetail: '업데이트 안내를 확인하세요. 아래 버튼은 현재 화면을 새로고칩니다.',
  manualRefresh: '화면 새로고침',
  otherApp: '다른 앱에서 열고 있음 — 브라우저에서 열고 설치하세요',
  otherAppDetail: '브라우저로 /admin/ai-center를 열어 설치 안내를 확인하세요.',
  iosManual: 'iPhone은 공유 버튼 > “홈 화면에 추가”로 설치하세요.',
  browserManual: '브라우저 메뉴(⋮) > “홈 화면에 추가” 또는 “앱 설치”로 설치하세요.',
  install: 'CocoTrip Control 설치',
  manualTitle: '수동 설치 안내',
  showGuide: '설치 안내 보기',
  installing: '설치 확인 중',
  declined: '설치를 취소했습니다. 원하면 아래 수동 설치 안내를 이용하세요.',
  failed: '설치를 마치지 못했습니다. 아래 수동 설치 안내를 이용해 주세요.',
};

type Copy = Record<keyof typeof ko, string>;

export const ownerControllerSetupCopy: Record<Language, Copy> = {
  ko,
  en: {
    title: 'Install owner controller', installed: 'Running Control in app mode',
    installAccepted: 'Home screen web app installation requested', reload: 'Refresh',
    updateLine: 'Web changes appear after deployment through an update notice or a refresh.',
    installDetail: 'See the installation guide below to open Control from your home screen.',
    updateTitle: 'Web screen updates',
    updateDetail: 'Check the update notice. The button below refreshes this screen.',
    manualRefresh: 'Refresh screen', otherApp: 'Opened in another app — use a browser to install',
    otherAppDetail: 'Open /admin/ai-center in your browser for installation instructions.',
    iosManual: 'On iPhone, use Share > Add to Home Screen.',
    browserManual: 'Use the browser menu (⋮) > Add to Home Screen or Install app.',
    install: 'Install CocoTrip Control', manualTitle: 'Manual installation guide', showGuide: 'Installation guide',
    installing: 'Checking installation', declined: 'Installation cancelled. You can use the manual guide below.',
    failed: 'Installation did not finish. Please use the manual guide below.',
  },
  ja: {
    title: 'オーナーコントローラーのインストール', installed: 'Control をアプリ画面で実行中',
    installAccepted: 'ホーム画面ウェブアプリのインストールをリクエスト済み', reload: '再読み込み',
    updateLine: 'ウェブ画面の変更は、公開後の更新案内または再読み込みで反映されます。',
    installDetail: 'ホーム画面から開くには、以下のインストール案内をご確認ください。',
    updateTitle: 'ウェブ画面の更新', updateDetail: '更新案内をご確認ください。下のボタンで現在の画面を再読み込みします。',
    manualRefresh: '画面を再読み込み', otherApp: '別のアプリで表示中 — ブラウザーで開いてインストールしてください',
    otherAppDetail: 'ブラウザーで /admin/ai-center を開き、インストール案内をご確認ください。',
    iosManual: 'iPhoneでは「共有」>「ホーム画面に追加」を選んでください。',
    browserManual: 'ブラウザーのメニュー（⋮）>「ホーム画面に追加」または「アプリをインストール」を選んでください。',
    install: 'CocoTrip Control をインストール', manualTitle: '手動インストール案内', showGuide: 'インストール案内',
    installing: 'インストールを確認中', declined: 'インストールをキャンセルしました。必要なら以下の手動案内をご利用ください。',
    failed: 'インストールを完了できませんでした。以下の手動案内をご利用ください。',
  },
  zh: {
    title: '安装管理控制器', installed: '正在以应用模式运行 Control',
    installAccepted: '已请求安装主屏幕网页应用', reload: '刷新',
    updateLine: '网页变更发布后，可通过更新提示或刷新查看。',
    installDetail: '如需从主屏幕直接打开，请查看下方安装说明。',
    updateTitle: '网页更新', updateDetail: '请查看更新提示。下方按钮会刷新当前页面。',
    manualRefresh: '刷新页面', otherApp: '正在其他应用中打开 — 请使用浏览器安装',
    otherAppDetail: '请在浏览器中打开 /admin/ai-center 并查看安装说明。',
    iosManual: 'iPhone 请使用“分享”>“添加到主屏幕”。',
    browserManual: '请使用浏览器菜单（⋮）>“添加到主屏幕”或“安装应用”。',
    install: '安装 CocoTrip Control', manualTitle: '手动安装说明', showGuide: '查看安装说明',
    installing: '正在确认安装', declined: '已取消安装。如有需要，可使用下方手动安装说明。',
    failed: '未能完成安装。请使用下方手动安装说明。',
  },
};
