import type { Language } from '@/i18n';

const ko = {
  title: '이 기기 알림',
  details: '권한과 연결 상태',
  permission: '브라우저 권한',
  registered: '기기 등록됨',
  unregistered: '기기 미등록',
  checking: '등록 확인 중',
  enrolling: '기기 등록 중',
  checkFailed: '등록 상태 확인 실패',
  enrollFailed: '기기 등록 실패',
  login: '로그인 필요',
  loginDetail: '관리자 계정으로 로그인한 뒤 이 기기를 등록할 수 있습니다.',
  loading: '로그인 확인 중',
  unavailable: '지원되지 않는 환경',
  unavailableDetail: '이 환경은 웹 알림을 지원하지 않습니다. 지원되는 Chrome 환경에서 다시 확인해 주세요.',
  denied: '알림 권한 차단됨',
  deniedDetail: '브라우저의 이 사이트 알림 설정을 허용으로 바꾼 뒤 다시 확인해 주세요.',
  notConfigured: '알림 연결 설정 필요',
  notConfiguredDetail: '사이트의 알림 연결 설정이 아직 준비되지 않았습니다.',
  registeredDetail: '이 브라우저의 구독과 현재 계정의 서버 등록을 확인했습니다. 실제 알림 수신은 별도 확인이 필요합니다.',
  unregisteredDetail: '등록 버튼을 누르면 브라우저에 알림 권한을 요청하고 이 기기를 현재 계정에 등록합니다.',
  checkFailedDetail: '서버 등록 상태를 확인하지 못했습니다. 연결을 확인한 뒤 다시 확인해 주세요.',
  enrollFailedDetail: '등록을 마치지 못했습니다. 권한과 연결을 확인한 뒤 다시 시도해 주세요.',
  pendingDetail: '브라우저 권한 창이나 네트워크 연결을 확인해 주세요. 진행 중인 등록이 끝나기 전에는 다시 요청하지 않습니다.',
  dispatch: '기기 등록만으로 서버 자동 발송이 켜지거나 실제 수신이 확인되는 것은 아닙니다. 서버 자동 알림 상태도 확인해 주세요.',
  enable: '이 기기 등록',
  check: '다시 확인',
  retry: '등록 재시도',
  permissions: { default: '요청 전', granted: '허용', denied: '차단', unsupported: '미지원' },
};

type Copy = { [K in keyof typeof ko]: typeof ko[K] extends string ? string : Record<keyof typeof ko[K], string> };

export const ownerNotificationCopy: Record<Language, Copy> = {
  ko,
  en: {
    title: 'Notifications on this device', details: 'Permission and connection', permission: 'Browser permission',
    registered: 'Device registered', unregistered: 'Device not registered', checking: 'Checking registration',
    enrolling: 'Registering device', checkFailed: 'Registration status unavailable', enrollFailed: 'Registration failed',
    login: 'Sign in required', loginDetail: 'Sign in with your administrator account to register this device.',
    loading: 'Checking sign-in', unavailable: 'Not supported here',
    unavailableDetail: 'This environment does not support web notifications. Check again in a supported Chrome environment.',
    denied: 'Notification permission blocked', deniedDetail: 'Allow notifications for this site in your browser settings, then check again.',
    notConfigured: 'Notification connection needs setup', notConfiguredDetail: 'The site notification connection is not configured yet.',
    registeredDetail: 'This browser subscription and its server registration for your current account were verified. Actual delivery still needs a separate check.',
    unregisteredDetail: 'Registering asks your browser for notification permission and saves this device to your current account.',
    checkFailedDetail: 'Server registration could not be verified. Check your connection and try checking again.',
    enrollFailedDetail: 'Registration did not finish. Check permission and your connection, then try again.',
    pendingDetail: 'Check the browser permission dialog or network connection. Another registration will not start while this one is pending.',
    dispatch: 'Registering this device does not enable automatic server alerts or prove delivery. Check the server alert status too.',
    enable: 'Register this device', check: 'Check again', retry: 'Retry registration',
    permissions: { default: 'Not requested', granted: 'Allowed', denied: 'Blocked', unsupported: 'Unsupported' },
  },
  ja: {
    title: 'この端末の通知', details: '権限と接続状態', permission: 'ブラウザーの権限',
    registered: '端末登録済み', unregistered: '端末未登録', checking: '登録状態を確認中',
    enrolling: '端末を登録中', checkFailed: '登録状態を確認できません', enrollFailed: '端末登録に失敗しました',
    login: 'ログインが必要です', loginDetail: '管理者アカウントでログインしてから、この端末を登録できます。',
    loading: 'ログインを確認中', unavailable: 'この環境では利用できません',
    unavailableDetail: 'この環境はウェブ通知に対応していません。対応するChrome環境で再確認してください。',
    denied: '通知の権限がブロックされています', deniedDetail: 'ブラウザーのサイト設定で通知を許可してから、再確認してください。',
    notConfigured: '通知接続の設定が必要です', notConfiguredDetail: 'サイトの通知接続はまだ設定されていません。',
    registeredDetail: 'このブラウザーの購読と、現在のアカウントのサーバー登録を確認しました。実際の受信確認は別途必要です。',
    unregisteredDetail: '登録ボタンでブラウザーに通知権限を要求し、この端末を現在のアカウントに登録します。',
    checkFailedDetail: 'サーバーの登録状態を確認できませんでした。接続を確認してから再確認してください。',
    enrollFailedDetail: '登録を完了できませんでした。権限と接続を確認してから再試行してください。',
    pendingDetail: 'ブラウザーの権限ダイアログまたはネットワーク接続を確認してください。処理中の登録が終わるまでは再要求しません。',
    dispatch: '端末登録だけではサーバーの自動通知は有効にならず、実際の受信も確認できません。サーバーの通知状態もご確認ください。',
    enable: 'この端末を登録', check: '再確認', retry: '登録を再試行',
    permissions: { default: '未要求', granted: '許可', denied: 'ブロック', unsupported: '非対応' },
  },
  zh: {
    title: '此设备的通知', details: '权限与连接状态', permission: '浏览器权限',
    registered: '设备已登记', unregistered: '设备未登记', checking: '正在检查登记状态',
    enrolling: '正在登记设备', checkFailed: '无法确认登记状态', enrollFailed: '设备登记失败',
    login: '需要登录', loginDetail: '请先登录管理员账号，再登记此设备。',
    loading: '正在检查登录状态', unavailable: '此环境不支持',
    unavailableDetail: '此环境不支持网页通知。请在支持的Chrome环境中重新检查。',
    denied: '通知权限已被阻止', deniedDetail: '请在浏览器的网站设置中允许通知，然后重新检查。',
    notConfigured: '需要设置通知连接', notConfiguredDetail: '网站的通知连接尚未配置。',
    registeredDetail: '已确认此浏览器的订阅及当前账号在服务器上的登记。实际接收通知仍需另行验证。',
    unregisteredDetail: '点击登记按钮将向浏览器请求通知权限，并将此设备登记到当前账号。',
    checkFailedDetail: '无法确认服务器上的登记状态。请检查网络连接后重试。',
    enrollFailedDetail: '登记未完成。请检查权限和网络连接后重试。',
    pendingDetail: '请检查浏览器权限弹窗或网络连接。当前登记结束前不会再次发起请求。',
    dispatch: '登记此设备并不会启用服务器自动通知，也不能证明已收到通知。请同时检查服务器通知状态。',
    enable: '登记此设备', check: '重新检查', retry: '重新登记',
    permissions: { default: '尚未请求', granted: '已允许', denied: '已阻止', unsupported: '不支持' },
  },
};
